const PC_TIERS = {
  low: {
    label: "Låg PC-prestanda",
    description: "Indie, 2D, lättare spel"
  },
  mid: {
    label: "Mellan-PC",
    description: "De flesta moderna spel på medium/hög"
  },
  high: {
    label: "High-end PC",
    description: "Tunga AAA-spel, hög upplösning"
  },
  extreme: {
    label: "Extreme PC",
    description: "Ray tracing, maxinställningar, framtidssäker"
  }
};

const DATA = {
personer: [
  "Fredrik","Danny","Odd","Natalie","Oscar",
  "Tony","Victoria","Fyghar","Peter","Emil",
  "Daniel","Robin","Jesper","Andres",
  "Mattias","Jim","Emilia","Arvid","Vanessa","Niclas"
],

  genrer: [
    "FPS / Action (Singel)",
    "Boomer shooters",
    "Looter shooters",
    "Taktisk FPS",
    "Battle Royale",
    "Hero shooter / MOBA-liknande FPS",
    "Stealth-spel (smygarspel)",
	"Action Adventure",
    "3D Plattformare",
    "2D Plattformare",
    "Pusselspel i förstaperson",
    "Physics-baserade spel / bygg- och experimentspel",
    "Metroidvania-spel",
    "RPG / CRPG",
    "JRPG",
    "Taktiskt RPG / Turbaserat taktiskt RPG",
    "ARPG / Action-rollspel",
    "Souls- och Soulslike",
    "Monsterfångar-RPG",
    "Open-World / Öppna världar",
    "Interactive Story / Episodspel",
    "Visuella noveller / Storybaserade spel",
    "Rogue-like / Rogue-lite spel",
    "Realtidsstrategi (RTS)",
    "Turbaserade strategispel (TBS)",
    "4X-strategi",
    "Grand Strategy",
    "Tower Defense",
    "MOBA / Tactical Arena / Auto-battler",
    "Card-based Strategy / Digital CCG",
    "Arkad- och Simcade Racing",
    "Kart-racing",
    "Full racing simulator",
    "Flygsimulator",
    "Övriga fordonsimulatorer",
    "Mech-/Robot-strategi eller action",
    "Ubåt / Rymdsimulatorer",
    "Sportspel",
    "Överlevnad / Crafting / Sandbox",
    "Sandbox / Creativity / World-building",
    "City building / Farming",
    "Life Simulation / Social Simulation",
    "Economy / Tycoon Games",
    "Skräckspel",
    "Walking Simulator i förstaperson",
    "Peka & Klicka Äventyr",
    "Survival Horror FPS",
    "Competitive Online (FPS etc.)",
    "Multiplayer / Coop",
    "MMO (Onlinespel)",
    "Partyspel / Micro-games",
    "Fighting",
    "Beat-em-Up / Brawler",
    "Arkadspel",
    "Klassiska arkadhallsspel",
    "Bullet hell / Shoot ’em up (Shmup)",
    "Rytmspel / Music / Rhythm action",
    "Match-3 spel",
    "Kortspel / Deckbuilding",
    "Tabletop / Digital Board Games"
  ],

  personerData: {

    Fredrik: {
		  plattformar: ["PC", "Playstation 5", "Xbox Series S|X", "Nintendo Switch", "Switch 2" ],
pcTier: "extreme",

  pc: {
    cpu: "Ryzen 9 9950X3D",
    gpu: "RTX 4090",
    ram: 32,
    notes: "Klarar alla typer av spel per 2025-12-19 - utifrån prestanda"
  },
      alskar: [
        "FPS / Action (Singel)",
		"Action Adventure",
        "3D Plattformare",
        "RPG / CRPG",
        "Open-World / Öppna världar",
        "Tower Defense",
        "Arkad- och Simcade Racing",
        "Överlevnad / Crafting / Sandbox",
        "City building / Farming",
        "Klassiska arkadhallsspel",
        "Bullet hell / Shoot ’em up (Shmup)",
        "Match-3 spel"
      ],
      oppen: [
        "FPS / Action (Singel)",
        "Boomer shooters",
        "Looter shooters",
        "3D Plattformare",
        "2D Plattformare",
        "Pusselspel i förstaperson",
        "Physics-baserade spel / bygg- och experimentspel",
        "Metroidvania-spel",
		"Rogue-like / Rogue-lite spel",
        "RPG / CRPG",
        "JRPG",
        "ARPG / Action-rollspel",
        "Souls- och Soulslike",
        "Monsterfångar-RPG",
        "Open-World / Öppna världar",
        "Realtidsstrategi (RTS)",
        "Turbaserade strategispel (TBS)",
        "4X-strategi",
        "Tower Defense",
        "Arkad- och Simcade Racing",
        "Kart-racing",
        "Sandbox / Creativity / World-building",
        "Life Simulation / Social Simulation",
        "Economy / Tycoon Games",
        "Skräckspel",
        "Peka & Klicka Äventyr",
        "Survival Horror FPS",
        "Beat-em-Up / Brawler",
        "Arkadspel",
        "Rytmspel / Music / Rhythm action"
      ],
      undviker: [
        "Battle Royale",
        "Hero shooter / MOBA-liknande FPS",
		"Taktisk FPS",
        "Stealth-spel (smygarspel)",
        "Visuella noveller / Storybaserade spel",
		"Interactive Story / Episodspel",
        "Grand Strategy",
        "MOBA / Tactical Arena / Auto-battler",
        "Card-based Strategy / Digital CCG",
        "Övriga fordonsimulatorer",
        "Mech-/Robot-strategi eller action",
        "Ubåt / Rymdsimulatorer",
		"Full racing simulator",
        "Sportspel",
		"Flygsimulator",
		"Partyspel / Micro-games",
        "Competitive Online (FPS etc.)",
        "Multiplayer / Coop",
        "MMO (Onlinespel)",
        "Fighting",
        "Kortspel / Deckbuilding",
        "Tabletop / Digital Board Games"
		],
		ejValt: [

      ]
    },

    Natalie: {
		plattformar: ["PC", "Playstation 5", ],
pcTier: "high",

  pc: {
    cpu: "Ryzen 5 9600X",
    gpu: "Radeon 6800 XT 16GB",
    ram: 32,
    notes: "Strax över mid-tier - nästan high. Bra allrounddator som är över genomsnittet."
  },
      alskar: [
        "RPG / CRPG",
        "Open-World / Öppna världar",
        "Överlevnad / Crafting / Sandbox",
        "Sandbox / Creativity / World-building",
        "City building / Farming",
        "Life Simulation / Social Simulation",
        "Economy / Tycoon Games"
      ],
      oppen: [
        "FPS / Action (Singel)",
        "Looter shooters",
        "Taktisk FPS",
        "Stealth-spel (smygarspel)",
		"Action Adventure",
        "3D Plattformare",
        "2D Plattformare",
        "Pusselspel i förstaperson",
        "Metroidvania-spel",
        "RPG / CRPG",
        "ARPG / Action-rollspel",
        "Souls- och Soulslike",
        "Open-World / Öppna världar",
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Rogue-like / Rogue-lite spel",
        "Grand Strategy",
        "Arkad- och Simcade Racing",
        "Övriga fordonsimulatorer",
        "Survival Horror FPS",
        "Multiplayer / Coop",
        "Klassiska arkadhallsspel"
      ],
      undviker: [
        "Boomer shooters",
        "Hero shooter / MOBA-liknande FPS",
        "Monsterfångar-RPG",
        "Turbaserade strategispel (TBS)",
        "Tower Defense",
        "MOBA / Tactical Arena / Auto-battler",
        "Card-based Strategy / Digital CCG",
        "Flygsimulator",
        "Mech-/Robot-strategi eller action",
        "Ubåt / Rymdsimulatorer",
        "Sportspel"
		],
		ejValt: [
  "Battle Royale",
  "Physics-baserade spel / bygg- och experimentspel",
  "JRPG",
  "Taktiskt RPG / Turbaserat taktiskt RPG",
  "Realtidsstrategi (RTS)",
  "4X-strategi",
  "Kart-racing",
  "Full racing simulator",
  "Skräckspel",
  "Walking Simulator i förstaperson",
  "Peka & Klicka Äventyr",
  "Competitive Online (FPS etc.)",
  "MMO (Onlinespel)",
  "Partyspel / Micro-games",
  "Fighting",
  "Beat-em-Up / Brawler",
  "Arkadspel",
  "Bullet hell / Shoot ’em up (Shmup)",
  "Rytmspel / Music / Rhythm action",
  "Match-3 spel",
  "Kortspel / Deckbuilding",
  "Tabletop / Digital Board Games"
      ]
    },

    Emil: {
		  plattformar: ["PC", ],
pcTier: "low",

  pc: {
    cpu: "Intel Core i7 4790K",
    gpu: "Radeon RX 6600 XT 8GB (snart)",
    ram: 16,
    notes: "Uppgradering av grafikkort möjliggör avsevärt fler spel.Dock hålls datorn tillbaka av föråldrad CPU. Dubbelkolla extra noga innan spel ges."
  },
      alskar: [
        "FPS / Action (Singel)",
        "Boomer shooters",
        "Taktisk FPS",
        "Pusselspel i förstaperson",
        "Souls- och Soulslike",
        "Realtidsstrategi (RTS)",
        "Ubåt / Rymdsimulatorer",
        "City building / Farming",
        "Economy / Tycoon Games",
        "Skräckspel",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Arkadspel",
        "Klassiska arkadhallsspel",
        "Bullet hell / Shoot ’em up (Shmup)",
        "Match-3 spel"
      ],
      oppen: [
        "FPS / Action (Singel)",
        "Taktisk FPS",
        "3D Plattformare",
        "2D Plattformare",
		"Action Adventure",
        "Rogue-like / Rogue-lite spel",
        "4X-strategi",
        "Arkad- och Simcade Racing",
        "Flygsimulator",
        "Överlevnad / Crafting / Sandbox",
        "Survival Horror FPS"
      ],
      undviker: [
        "Looter shooters",
        "Battle Royale",
        "Hero shooter / MOBA-liknande FPS",
        "JRPG",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "Sportspel",
        "Competitive Online (FPS etc.)",
        "Multiplayer / Coop",
        "MMO (Onlinespel)",
        "Partyspel / Micro-games",
        "Fighting",
        "Beat-em-Up / Brawler",
        "Tabletop / Digital Board Games"
		],
		ejValt: [
  "Stealth-spel (smygarspel)",
  "Physics-baserade spel / bygg- och experimentspel",
  "Metroidvania-spel",
  "RPG / CRPG",
  "ARPG / Action-rollspel",
  "Monsterfångar-RPG",
  "Open-World / Öppna världar",
  "Interactive Story / Episodspel",
  "Visuella noveller / Storybaserade spel",
  "Turbaserade strategispel (TBS)",
  "Grand Strategy",
  "Tower Defense",
  "MOBA / Tactical Arena / Auto-battler",
  "Card-based Strategy / Digital CCG",
  "Kart-racing",
  "Full racing simulator",
  "Övriga fordonsimulatorer",
  "Mech-/Robot-strategi eller action",
  "Sandbox / Creativity / World-building",
  "Life Simulation / Social Simulation",
  "Rytmspel / Music / Rhythm action",
  "Kortspel / Deckbuilding"
      ]
    },

    Victoria: {
		  plattformar: ["PC", "Playstation 5", "Nintendo Switch", ],
pcTier: "low",

  pc: {
    cpu: "Intel Core",
    gpu: "Nvidia Geforce RTX 2060 Super 8GB",
    ram: 16,
    notes: "Grafikkortet är dugligt, men överlag en svag dator. Inväntar ny HW Info undersökning."
  },	
	
      alskar: [
        "RPG / CRPG",
        "JRPG",
		"Action Adventure",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "Monsterfångar-RPG",
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Life Simulation / Social Simulation",
        "Economy / Tycoon Games",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Tabletop / Digital Board Games"
      ],
      oppen: [
        "Stealth-spel (smygarspel)",
        "3D Plattformare",
        "2D Plattformare",
        "Pusselspel i förstaperson",
        "RPG / CRPG",
        "JRPG",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "ARPG / Action-rollspel",
        "Monsterfångar-RPG",
        "Open-World / Öppna världar",
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Rogue-like / Rogue-lite spel",
        "Turbaserade strategispel (TBS)",
        "Card-based Strategy / Digital CCG",
        "Överlevnad / Crafting / Sandbox",
        "Sandbox / Creativity / World-building",
        "City building / Farming",
        "Life Simulation / Social Simulation",
        "Economy / Tycoon Games",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Partyspel / Micro-games",
        "Beat-em-Up / Brawler",
        "Arkadspel",
        "Rytmspel / Music / Rhythm action",
        "Match-3 spel",
        "Kortspel / Deckbuilding",
        "Tabletop / Digital Board Games"
      ],
      undviker: [
        "FPS / Action (Singel)",
        "Boomer shooters",
        "Battle Royale",
        "Hero shooter / MOBA-liknande FPS",
        "Physics-baserade spel / bygg- och experimentspel",
        "Metroidvania-spel",
        "Souls- och Soulslike",
        "Realtidsstrategi (RTS)",
        "4X-strategi",
        "Grand Strategy",
        "MOBA / Tactical Arena / Auto-battler",
        "Arkad- och Simcade Racing",
        "Full racing simulator",
        "Sportspel",
        "Skräckspel",
        "Survival Horror FPS",
        "Competitive Online (FPS etc.)",
        "Fighting",
        "Bullet hell / Shoot ’em up (Shmup)"
		],
		ejValt: [
  "Looter shooters",
  "Taktisk FPS",
  "Tower Defense",
  "Kart-racing",
  "Flygsimulator",
  "Övriga fordonsimulatorer",
  "Mech-/Robot-strategi eller action",
  "Ubåt / Rymdsimulatorer",
  "Multiplayer / Coop",
  "MMO (Onlinespel)",
  "Klassiska arkadhallsspel"
      ]
    },
	    Danny: {
		  plattformar: ["PC", "Playstation 5", "Xbox Series S|X", ],
pcTier: "mid",

  pc: {
    cpu: "Intel Core i5 11400F",
    gpu: "Radeon RX 6750 XT 12GB",
    ram: 32,
    notes: "Okej allrounddator. Om än på väg att bli lite väl till åren. Grafikkortets VRAM gör att den höjer sig över genomsnittet."
  },
			
      alskar: [
        "FPS / Action (Singel)",
        "Looter shooters",
        "Stealth-spel (smygarspel)",
		"Action Adventure",
        "3D Plattformare",
        "2D Plattformare",
        "Metroidvania-spel",
        "RPG / CRPG",
        "JRPG",
        "ARPG / Action-rollspel",
        "Open-World / Öppna världar",
        "Arkad- och Simcade Racing",
        "Kart-racing",
        "Skräckspel",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Survival Horror FPS",
        "Multiplayer / Coop",
        "Beat-em-Up / Brawler",
        "Arkadspel",
        "Klassiska arkadhallsspel"
      ],
      oppen: [
        "Boomer shooters",
        "Pusselspel i förstaperson",
        "Physics-baserade spel / bygg- och experimentspel",
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Realtidsstrategi (RTS)",
        "Full racing simulator",
        "Mech-/Robot-strategi eller action",
        "Överlevnad / Crafting / Sandbox",
        "Sandbox / Creativity / World-building",
        "Bullet hell / Shoot ’em up (Shmup)",
		"Monsterfångar-RPG",
		"Flygsimulator",
		"Övriga fordonsimulatorer",
		"Ubåt / Rymdsimulatorer",
		"City building / Farming",
		"Life Simulation / Social Simulation",
		"Partyspel / Micro-games"
      ],
      undviker: [
        "Taktisk FPS",
        "Battle Royale",
        "Hero shooter / MOBA-liknande FPS",
        "Rogue-like / Rogue-lite spel",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "Souls- och Soulslike",
        "Turbaserade strategispel (TBS)",
        "4X-strategi",
        "Grand Strategy",
        "Tower Defense",
        "MOBA / Tactical Arena / Auto-battler",
        "Card-based Strategy / Digital CCG",
        "Sportspel",
        "Economy / Tycoon Games",
        "Competitive Online (FPS etc.)",
        "MMO (Onlinespel)",
        "Fighting",
        "Rytmspel / Music / Rhythm action",
        "Match-3 spel",
        "Kortspel / Deckbuilding",
        "Tabletop / Digital Board Games"
		],
		ejValt: [

      ]
    },

    Odd: {
		  plattformar: ["PC", "Playstation 5", "Xbox Series S|X", "Nintendo Switch", ],
pcTier: "mid",

  pc: {
    cpu: "Ryzen 7 5800X3D",
    gpu: "Nvidia Geforce RTX 2080 Ti 11GB",
    ram: 32,
    notes: "Bra allroundmaskin - även om GPU är något föråldrad. Vägs däremot upp av att ha gott om VRAM."
  },
      alskar: [
        "FPS / Action (Singel)",
        "Boomer shooters",
        "Looter shooters",
        "Taktisk FPS",
        "Battle Royale",
        "Stealth-spel (smygarspel)",
		"Action Adventure",
        "3D Plattformare",
        "2D Plattformare",
        "Pusselspel i förstaperson",
        "Metroidvania-spel",
        "RPG / CRPG",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "ARPG / Action-rollspel",
        "Souls- och Soulslike",
        "Open-World / Öppna världar",
        "Realtidsstrategi (RTS)",
        "Turbaserade strategispel (TBS)",
        "Tower Defense",
        "MOBA / Tactical Arena / Auto-battler",
        "Mech-/Robot-strategi eller action",
        "Ubåt / Rymdsimulatorer",
        "Överlevnad / Crafting / Sandbox",
        "City building / Farming",
        "Skräckspel",
        "Survival Horror FPS",
        "Multiplayer / Coop",
        "Fighting",
        "Bullet hell / Shoot ’em up (Shmup)",
        "Rytmspel / Music / Rhythm action"
      ],
      oppen: [
        "FPS / Action (Singel)",
        "Boomer shooters",
        "Looter shooters",
        "Taktisk FPS",
        "Battle Royale",
        "Hero shooter / MOBA-liknande FPS",
        "Stealth-spel (smygarspel)",
        "3D Plattformare",
        "2D Plattformare",
        "Pusselspel i förstaperson",
        "Physics-baserade spel / bygg- och experimentspel",
        "Metroidvania-spel",
        "RPG / CRPG",
        "JRPG",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "ARPG / Action-rollspel",
        "Souls- och Soulslike",
        "Monsterfångar-RPG",
        "Open-World / Öppna världar",
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Rogue-like / Rogue-lite spel",
        "Realtidsstrategi (RTS)",
        "Turbaserade strategispel (TBS)",
        "4X-strategi",
        "Grand Strategy",
        "Tower Defense",
        "MOBA / Tactical Arena / Auto-battler",
        "Card-based Strategy / Digital CCG",
        "Arkad- och Simcade Racing",
        "Kart-racing",
        "Mech-/Robot-strategi eller action",
        "Ubåt / Rymdsimulatorer",
        "Sportspel",
        "Överlevnad / Crafting / Sandbox",
        "Sandbox / Creativity / World-building",
        "City building / Farming",
        "Economy / Tycoon Games",
        "Skräckspel",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Survival Horror FPS",
        "Competitive Online (FPS etc.)",
        "Multiplayer / Coop",
        "MMO (Onlinespel)",
        "Partyspel / Micro-games",
        "Fighting",
        "Beat-em-Up / Brawler",
        "Arkadspel",
        "Klassiska arkadhallsspel",
        "Bullet hell / Shoot ’em up (Shmup)",
        "Rytmspel / Music / Rhythm action",
        "Kortspel / Deckbuilding",
        "Tabletop / Digital Board Games"
      ],
      undviker: [
        "Full racing simulator",
        "Flygsimulator",
        "Life Simulation / Social Simulation",
        "Match-3 spel"
      ]
    },

    Peter: {
		  plattformar: ["PC", "Playstation 5", "Xbox Series S|X", ],
pcTier: "mid",

  pc: {
    cpu: "Ryzen 5 5600",
    gpu: "Radeon RX 6600 XT 8GB",
    ram: 16,
    notes: "God allroundmaskin sedan uppgradering av grafikkort."
  },
      alskar: [
        "Looter shooters",
        "RPG / CRPG",
        "ARPG / Action-rollspel",
        "Souls- och Soulslike",
		"Action Adventure",
        "Open-World / Öppna världar",
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Överlevnad / Crafting / Sandbox",
        "Skräckspel",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Survival Horror FPS",
        "Tabletop / Digital Board Games"
      ],
      oppen: [
        "FPS / Action (Singel)",
        "Battle Royale",
        "Rogue-like / Rogue-lite spel",
        "4X-strategi",
        "Card-based Strategy / Digital CCG",
        "Arkad- och Simcade Racing",
        "Sportspel",
        "Competitive Online (FPS etc.)",
        "Multiplayer / Coop",
        "Bullet hell / Shoot ’em up (Shmup)"
      ],
      undviker: [
        "3D Plattformare",
        "2D Plattformare",
        "JRPG",
        "Realtidsstrategi (RTS)",
        "Kart-racing",
        "Fighting",
        "Beat-em-Up / Brawler"
		],
		ejValt: [
  "Boomer shooters",
  "Taktisk FPS",
  "Hero shooter / MOBA-liknande FPS",
  "Stealth-spel (smygarspel)",
  "Pusselspel i förstaperson",
  "Physics-baserade spel / bygg- och experimentspel",
  "Metroidvania-spel",
  "Taktiskt RPG / Turbaserat taktiskt RPG",
  "Monsterfångar-RPG",
  "Turbaserade strategispel (TBS)",
  "Grand Strategy",
  "Tower Defense",
  "MOBA / Tactical Arena / Auto-battler",
  "Full racing simulator",
  "Flygsimulator",
  "Övriga fordonsimulatorer",
  "Mech-/Robot-strategi eller action",
  "Ubåt / Rymdsimulatorer",
  "Sandbox / Creativity / World-building",
  "City building / Farming",
  "Life Simulation / Social Simulation",
  "Economy / Tycoon Games",
  "MMO (Onlinespel)",
  "Partyspel / Micro-games",
  "Arkadspel",
  "Klassiska arkadhallsspel",
  "Rytmspel / Music / Rhythm action",
  "Match-3 spel",
  "Kortspel / Deckbuilding"
      ]
    },

    Oscar: {
		  plattformar: ["PC", "Xbox Series S|X", "Nintendo Switch", "Switch 2" ],
pcTier: "mid",

  pc: {
    cpu: "AMD Ryzen 5 9600X",
    gpu: "Intel ARC B580 12GB",
    ram: 32,
    notes: "Bra för alla typer av spel utifrån råprestanda. Obs! Dubbelkolla spelstöd för Intel ARC!"
  },
      alskar: [
        "FPS / Action (Singel)",
        "3D Plattformare",
        "2D Plattformare",
        "Pusselspel i förstaperson",
        "RPG / CRPG",
        "JRPG",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "ARPG / Action-rollspel",
        "Monsterfångar-RPG",
        "Open-World / Öppna världar",
        "Visuella noveller / Storybaserade spel",
        "Turbaserade strategispel (TBS)",
        "Card-based Strategy / Digital CCG",
        "Arkad- och Simcade Racing",
        "Kart-racing",
        "Full racing simulator",
        "Övriga fordonsimulatorer",
        "City building / Farming",
        "Life Simulation / Social Simulation",
        "Economy / Tycoon Games",
        "Peka & Klicka Äventyr",
        "Partyspel / Micro-games",
        "Arkadspel",
        "Klassiska arkadhallsspel",
        "Kortspel / Deckbuilding"
      ],
      oppen: [
        "Taktisk FPS",
        "Metroidvania-spel",
        "Rogue-like / Rogue-lite spel",
        "4X-strategi",
        "Grand Strategy",
		"Action Adventure",
        "Överlevnad / Crafting / Sandbox",
        "Sandbox / Creativity / World-building",
        "MMO (Onlinespel)",
        "Bullet hell / Shoot ’em up (Shmup)",
        "Match-3 spel"
      ],
      undviker: [
        "Boomer shooters",
        "Souls- och Soulslike",
        "MOBA / Tactical Arena / Auto-battler",
        "Flygsimulator",
        "Skräckspel",
        "Competitive Online (FPS etc.)",
        "Rytmspel / Music / Rhythm action",
        "Tabletop / Digital Board Games"
		],
		ejValt: [
  "Looter shooters",
  "Battle Royale",
  "Hero shooter / MOBA-liknande FPS",
  "Stealth-spel (smygarspel)",
  "Physics-baserade spel / bygg- och experimentspel",
  "Interactive Story / Episodspel",
  "Realtidsstrategi (RTS)",
  "Tower Defense",
  "Mech-/Robot-strategi eller action",
  "Ubåt / Rymdsimulatorer",
  "Sportspel",
  "Walking Simulator i förstaperson",
  "Survival Horror FPS",
  "Multiplayer / Coop",
  "Fighting",
  "Beat-em-Up / Brawler"
      ]
    },

    Fyghar: {
		  plattformar: ["PC", "Playstation 5", "Nintendo Switch", ],
pcTier: "low",

  pc: {
    cpu: "Ryzen 5 2600",
    gpu: "Nvidia Geforce RTX 3060 12GB",
    ram: 16,
    notes: "Okej dator, grafikkort är dock föråldrat, även om det har större mängd VRAM än genomsnittet."
  },
      alskar: [
        "RPG / CRPG",
        "Monsterfångar-RPG",
        "Arkad- och Simcade Racing",
        "Kart-racing",
		"Action Adventure",
        "Multiplayer / Coop",
        "Partyspel / Micro-games",
        "Beat-em-Up / Brawler"
      ],
      oppen: [
        "FPS / Action (Singel)",
        "Boomer shooters",
        "Looter shooters",
        "Taktisk FPS",
        "3D Plattformare",
        "2D Plattformare",
        "Physics-baserade spel / bygg- och experimentspel",
        "Metroidvania-spel",
        "JRPG",
        "Taktiskt RPG / Turbaserat taktiskt RPG",
        "ARPG / Action-rollspel",
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Rogue-like / Rogue-lite spel",
        "Turbaserade strategispel (TBS)",
        "4X-strategi",
        "Tower Defense",
        "Card-based Strategy / Digital CCG",
        "Övriga fordonsimulatorer",
        "City building / Farming",
        "Life Simulation / Social Simulation",
        "Economy / Tycoon Games",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Arkadspel",
        "Klassiska arkadhallsspel",
        "Bullet hell / Shoot ’em up (Shmup)",
        "Rytmspel / Music / Rhythm action",
        "Match-3 spel",
        "Kortspel / Deckbuilding",
        "Tabletop / Digital Board Games"
      ],
      undviker: [
        "Hero shooter / MOBA-liknande FPS",
        "Souls- och Soulslike",
        "Skräckspel",
        "Survival Horror FPS",
        "Competitive Online (FPS etc.)",
        "MMO (Onlinespel)"
		],
		ejValt: [
  "Battle Royale",
  "Stealth-spel (smygarspel)",
  "Pusselspel i förstaperson",
  "Open-World / Öppna världar",
  "Realtidsstrategi (RTS)",
  "Grand Strategy",
  "MOBA / Tactical Arena / Auto-battler",
  "Full racing simulator",
  "Flygsimulator",
  "Mech-/Robot-strategi eller action",
  "Ubåt / Rymdsimulatorer",
  "Sportspel"
      ]
    },

    Tony: {
		  plattformar: ["PC", "Playstation 5", "Nintendo Switch", ],
pcTier: "high",

  pc: {
    cpu: "Intel(R) Core i7-12700F",
    gpu: "Nvidia GeForce RTX 4070 12GB",
    ram: 32,
    notes: "Bra för alla typer av spel - utifrån prestanda"
  },
      alskar: [
        "Looter shooters",
        "RPG / CRPG",
        "Souls- och Soulslike",
        "MOBA / Tactical Arena / Auto-battler",
        "MMO (Onlinespel)"
      ],
      oppen: [
        "FPS / Action (Singel)",
		"Action Adventure",
        "Metroidvania-spel",
		"2D Plattformare",
        "Open-World / Öppna världar",
		"JRPG",
		"ARPG / Action-rollspel",
        "Rogue-like / Rogue-lite spel",
		"Card-based Strategy / Digital CCG",
		"Hero shooter / MOBA-liknande FPS",
        "Realtidsstrategi (RTS)",
        "Turbaserade strategispel (TBS)",
		"Klassiska arkadhallsspel",
        "Tower Defense",
        "Kart-racing",
        "Fighting",
        "Beat-em-Up / Brawler",
		"Bullet hell / Shoot ’em up (Shmup)",
        "Kortspel / Deckbuilding"
      ],
      undviker: [
        "Interactive Story / Episodspel",
        "Visuella noveller / Storybaserade spel",
        "Sportspel",
        "Skräckspel",
        "Rytmspel / Music / Rhythm action",
        "Tabletop / Digital Board Games"
		],
		ejValt: [
  "Boomer shooters",
  "Taktisk FPS",
  "Battle Royale",
  "Stealth-spel (smygarspel)",
  "3D Plattformare",
  "Pusselspel i förstaperson",
  "Physics-baserade spel / bygg- och experimentspel",
  "Taktiskt RPG / Turbaserat taktiskt RPG",
  "Monsterfångar-RPG",
  "Grand Strategy",
  "Arkad- och Simcade Racing",
  "Full racing simulator",
  "Flygsimulator",
  "Övriga fordonsimulatorer",
  "Mech-/Robot-strategi eller action",
  "Ubåt / Rymdsimulatorer",
  "Överlevnad / Crafting / Sandbox",
  "Sandbox / Creativity / World-building",
  "City building / Farming",
  "Life Simulation / Social Simulation",
  "Economy / Tycoon Games",
  "Walking Simulator i förstaperson",
  "Peka & Klicka Äventyr",
  "Survival Horror FPS",
  "Competitive Online (FPS etc.)",
  "Multiplayer / Coop",
  "Partyspel / Micro-games",
  "Arkadspel",
  "Match-3 spel"
      ]
    },

Daniel: {
  plattformar: ["Playstation 5", "Xbox Series S|X", "Nintendo Switch"],

  alskar: [
        "FPS / Action (Singel)",
        "Boomer shooters",
        "Looter shooters",
		"Action Adventure",
        "Stealth-spel (smygarspel)",
        "3D Plattformare",
        "2D Plattformare",
        "Pusselspel i förstaperson",
        "Metroidvania-spel",
        "RPG / CRPG",
        "JRPG",
        "ARPG / Action-rollspel",
        "Souls- och Soulslike",
        "Open-World / Öppna världar",
        "Interactive Story / Episodspel",
        "Realtidsstrategi (RTS)",
        "Turbaserade strategispel (TBS)",
        "4X-strategi",
        "Grand Strategy",
        "Arkad- och Simcade Racing",
        "Kart-racing",
        "Full racing simulator",
        "Mech-/Robot-strategi eller action",
        "Ubåt / Rymdsimulatorer",
        "Överlevnad / Crafting / Sandbox",
        "Sandbox / Creativity / World-building",
        "Skräckspel",
        "Survival Horror FPS",
        "Walking Simulator i förstaperson",
        "Peka & Klicka Äventyr",
        "Partyspel / Micro-games",
        "Fighting",
        "Beat-em-Up / Brawler",
        "Arkadspel",
        "Klassiska arkadhallsspel",
        "Bullet hell / Shoot ’em up (Shmup)",
        "Rytmspel / Music / Rhythm action",
        "Match-3 spel",
        "Tabletop / Digital Board Games"
      ],
      oppen: [
        "Taktisk FPS",
        "Battle Royale",
        "Hero shooter / MOBA-liknande FPS",
        "Physics-baserade spel / bygg- och experimentspel",
        "Monsterfångar-RPG",
		"Rogue-like / Rogue-lite spel",
        "Tower Defense",
        "MOBA / Tactical Arena / Auto-battler",
        "Card-based Strategy / Digital CCG",
        "Flygsimulator",
        "Övriga fordonsimulatorer",
		"Full racing simulator",
        "Sportspel",
        "City building / Farming",
        "Life Simulation / Social Simulation",
		"Visuella noveller / Storybaserade spel",
        "Economy / Tycoon Games",
        "Competitive Online (FPS etc.)",
        "Multiplayer / Coop",
        "MMO (Onlinespel)",
        "Kortspel / Deckbuilding"
      ],
      undviker: [
        "Hero shooter / MOBA-liknande FPS",
        "MOBA / Tactical Arena / Auto-battler",
        "Card-based Strategy / Digital CCG",
		"Överlevnad / Crafting / Sandbox",
		"Sandbox / Creativity / World-building",
		"Tower Defense",
        "Övriga fordonsimulatorer",
        "Sportspel",
        "Life Simulation / Social Simulation",
        "Competitive Online (FPS etc.)",
        "Multiplayer / Coop",
        "MMO (Onlinespel)",
        "Kortspel / Deckbuilding",
		"City building / Farming",
  		"Economy / Tycoon Games",
  		"Match-3 spel"
		],
		ejValt: [
  
      ]
	},
Robin: {
		  plattformar: ["PC", ],
pcTier: "mid",

  pc: {
    cpu: "Intel Core i7-13700f",
    gpu: "Nvidia Geforce RTX 3070 8GB",
    ram: 16,
    notes: "God allroundmaskin, tänk dock på att RTX 3070 enbart har 8GB VRAM."
  },
  alskar: [
    "FPS / Action (Singel)",
    "Boomer shooters",
    "Looter shooters",
    "Taktisk FPS",
    "Battle Royale",
	"Action Adventure",
    "Stealth-spel (smygarspel)",
    "Pusselspel i förstaperson",
    "Physics-baserade spel / bygg- och experimentspel",
    "RPG / CRPG",
    "Taktiskt RPG / Turbaserat taktiskt RPG",
    "ARPG / Action-rollspel",
    "Souls- och Soulslike",
    "Open-World / Öppna världar",
    "Rogue-like / Rogue-lite spel",
    "4X-strategi",
    "Grand Strategy",
    "Tower Defense",
    "Arkad- och Simcade Racing",
    "Övriga fordonsimulatorer",
    "Överlevnad / Crafting / Sandbox",
    "Sandbox / Creativity / World-building",
    "City building / Farming",
    "Life Simulation / Social Simulation",
    "Economy / Tycoon Games",
    "Skräckspel",
    "Survival Horror FPS",
    "Competitive Online (FPS etc.)",
    "MMO (Onlinespel)",
    "Bullet hell / Shoot ’em up (Shmup)"
  ],

  oppen: [
    "Hero shooter / MOBA-liknande FPS",
    "JRPG",
    "Souls- och Soulslike",
    "Realtidsstrategi (RTS)",
    "MOBA / Tactical Arena / Auto-battler",
    "Mech-/Robot-strategi eller action",
    "Ubåt / Rymdsimulatorer",
    "Peka & Klicka Äventyr"
  ],

  undviker: [
    "Interactive Story / Episodspel",
    "Visuella noveller / Storybaserade spel",
    "Card-based Strategy / Digital CCG",
    "Kart-racing",
    "Full racing simulator",
    "Flygsimulator",
    "Sportspel",
    "Walking Simulator i förstaperson",
    "Partyspel / Micro-games",
    "Fighting",
    "Arkadspel",
    "Klassiska arkadhallsspel",
    "Rytmspel / Music / Rhythm action",
    "Match-3 spel",
    "Kortspel / Deckbuilding",
    "Tabletop / Digital Board Games"
	],
	ejValt: [
  "3D Plattformare",
  "2D Plattformare",
  "Metroidvania-spel",
  "Multiplayer / Coop"
      ]
    },
	Jesper: {
		  plattformar: ["PC", "Playstation 5", "Xbox Series S|X", "Nintendo Switch", "Switch 2" ],
pcTier: "mid",

  pc: {
    cpu: "Intel Core i7-12650H",
    gpu: "Nvidia Geforce RTX 3060",
    ram: 16,
    notes: "Obs! Var uppmärksamma kring systemkrav. En laptops grafikkort är ej jämbördigt med en stationär dators motsvarighet. En laptop med RTX 3060 är jämbördigt med RTX 3050 på en stationär dator."
  },
  alskar: [
    "RPG / CRPG",
    "JRPG",
    "Monsterfångar-RPG",
    "Walking Simulator i förstaperson"
  ],

  oppen: [
    "FPS / Action (Singel)",
    "Boomer shooters",
    "Looter shooters",
	"Action Adventure",
    "3D Plattformare",
    "2D Plattformare",
    "Metroidvania-spel",
    "Taktiskt RPG / Turbaserat taktiskt RPG",
    "ARPG / Action-rollspel",
    "Souls- och Soulslike",
    "Open-World / Öppna världar",
    "Interactive Story / Episodspel",
    "Visuella noveller / Storybaserade spel",
    "Rogue-like / Rogue-lite spel",
    "Arkad- och Simcade Racing",
    "Kart-racing",
    "Skräckspel",
    "Survival Horror FPS",
    "MMO (Onlinespel)",
    "Partyspel / Micro-games",
    "Fighting",
    "Beat-em-Up / Brawler",
    "Arkadspel",
    "Klassiska arkadhallsspel",
    "Bullet hell / Shoot ’em up (Shmup)",
    "Rytmspel / Music / Rhythm action"
  ],

  undviker: [
    "Taktisk FPS",
    "Battle Royale",
    "Hero shooter / MOBA-liknande FPS",
    "Stealth-spel (smygarspel)",
    "Pusselspel i förstaperson",
    "Physics-baserade spel / bygg- och experimentspel",
    "Realtidsstrategi (RTS)",
    "Turbaserade strategispel (TBS)",
    "4X-strategi",
    "Grand Strategy",
    "Tower Defense",
    "MOBA / Tactical Arena / Auto-battler",
    "Card-based Strategy / Digital CCG",
    "Full racing simulator",
    "Flygsimulator",
    "Övriga fordonsimulatorer",
    "Ubåt / Rymdsimulatorer",
    "Sportspel",
    "Överlevnad / Crafting / Sandbox",
    "Sandbox / Creativity / World-building",
    "City building / Farming",
    "Life Simulation / Social Simulation",
    "Economy / Tycoon Games",
    "Peka & Klicka Äventyr",
    "Competitive Online (FPS etc.)",
	"Multiplayer / Coop",
    "Mech-/Robot-strategi eller action",
    "Tabletop / Digital Board Games",
	"Match-3 spel",
    "Kortspel / Deckbuilding"
	],
	  ejValt: [
   
  ]
},
Andres: {
		  plattformar: ["PC", "Xbox Series S|X",  "Nintendo Switch" ],
pcTier: "mid",

  pc: {
    cpu: "Intel Core i7-13700f",
    gpu: "Nvidia Geforce RTX 3070 8GB",
    ram: 32,
    notes: "God allroundmaskin, tänk dock på att RTX 3070 enbart har 8GB VRAM."
  },
  alskar: [
    "FPS / Action (Singel)",
    "Boomer shooters",
    "Looter shooters",
	"Action Adventure",
    "Stealth-spel (smygarspel)",
    "2D Plattformare",
    "Metroidvania-spel",
    "RPG / CRPG",
    "ARPG / Action-rollspel",
	"Beat-em-Up / Brawler",
    "Souls- och Soulslike",
    "Rogue-like / Rogue-lite spel",
    "Realtidsstrategi (RTS)",
    "Turbaserade strategispel (TBS)",
    "4X-strategi",
    "Arkad- och Simcade Racing",
    "Mech-/Robot-strategi eller action",
    "Ubåt / Rymdsimulatorer",
    "Överlevnad / Crafting / Sandbox",
    "Sandbox / Creativity / World-building",
    "City building / Farming",
    "Skräckspel",
    "Survival Horror FPS",
    "Competitive Online (FPS etc.)",
    "Multiplayer / Coop",
    "Arkadspel",
    "Klassiska arkadhallsspel",
    "Bullet hell / Shoot ’em up (Shmup)",
    "Rytmspel / Music / Rhythm action"
  ],

  oppen: [
    "Looter shooters",
	"3D Plattformare",
	"Open-World / Öppna världar",
    "Taktisk FPS",
    "Battle Royale",
    "Hero shooter / MOBA-liknande FPS",
    "Pusselspel i förstaperson",
    "Physics-baserade spel / bygg- och experimentspel",
    "JRPG",
    "Taktiskt RPG / Turbaserat taktiskt RPG",
    "Grand Strategy",
    "Tower Defense",
	"Sportspel",
	"Fighting",
	"MMO (Onlinespel)",
    "MOBA / Tactical Arena / Auto-battler",
	"Kart-racing",
    "Full racing simulator",
    "Flygsimulator",
    "Övriga fordonsimulatorer",
    "Economy / Tycoon Games",
    "Walking Simulator i förstaperson",
    "Peka & Klicka Äventyr",
	"Match-3 spel",
	"Kortspel / Deckbuilding"
  ],

  undviker: [
    "Monsterfångar-RPG",
    "Visuella noveller / Storybaserade spel",
	"Interactive Story / Episodspel",
	"Partyspel / Micro-games",
    "Card-based Strategy / Digital CCG",
    "Life Simulation / Social Simulation",
    "Tabletop / Digital Board Games"
	],
	ejValt: [
 
  ]
},
Mattias: {
		  plattformar: ["PC", "Playstation 5", "Nintendo Switch", ],
pcTier: "high",

  pc: {
    cpu: "Intel Core i7 10700K",
    gpu: "Radeon RX 9060 XT 16 GB",
    ram: 16,
    notes: "Bra allrounddator - särskilt pga det nya grafikkort. CPU-krävande spel kan potentiellt vara stoppklossar - men troligtvis kommer det ej vara något problem."
  },
  alskar: [
  "FPS / Action (Singel)",
  "Boomer shooters",
  "Action Adventure",
  "RPG / CRPG",
  "Open-World / Öppna världar",
  "Arkad- och Simcade Racing",
  "Skräckspel",
  "Walking Simulator i förstaperson",
  "Peka & Klicka Äventyr",
  "Arkadspel"
],

oppen: [
  "Looter shooters",
  "Taktisk FPS",
  "Stealth-spel (smygarspel)",
  "3D Plattformare",
  "2D Plattformare",
  "Pusselspel i förstaperson",
  "Metroidvania-spel",
  "Taktiskt RPG / Turbaserat taktiskt RPG",
  "ARPG / Action-rollspel",
  "Souls- och Soulslike",
  "Interactive Story / Episodspel",
  "Rogue-like / Rogue-lite spel",
  "Turbaserade strategispel (TBS)",
  "Full racing simulator",
  "Sportspel",
  "Survival Horror FPS",
  "Multiplayer / Coop",
  "Beat-em-Up / Brawler",
  "Klassiska arkadhallsspel",
  "Bullet hell / Shoot ’em up (Shmup)"
],

undviker: [
  "Battle Royale",
  "Hero shooter / MOBA-liknande FPS",
  "Physics-baserade spel / bygg- och experimentspel",
  "JRPG",
  "Monsterfångar-RPG",
  "Visuella noveller / Storybaserade spel",
  "Realtidsstrategi (RTS)",
  "4X-strategi",
  "Grand Strategy",
  "Tower Defense",
  "MOBA / Tactical Arena / Auto-battler",
  "Card-based Strategy / Digital CCG",
  "Kart-racing",
  "Flygsimulator",
  "Övriga fordonsimulatorer",
  "Mech-/Robot-strategi eller action",
  "Ubåt / Rymdsimulatorer",
  "Sandbox / Creativity / World-building",
  "City building / Farming",
  "Life Simulation / Social Simulation",
  "Economy / Tycoon Games",
  "Competitive Online (FPS etc.)",
  "MMO (Onlinespel)",
  "Partyspel / Micro-games",
  "Fighting",
  "Rytmspel / Music / Rhythm action",
  "Match-3 spel",
  "Kortspel / Deckbuilding",
  "Tabletop / Digital Board Games"
],

ejValt: [
  "Överlevnad / Crafting / Sandbox"
]

},

Jim: {
  plattformar: ["PC"],
  pcTier: "mid",

  pc: {
    cpu: "Intel Core i7 14700F",
    gpu: "Nvidia Geforce RTX 4060 8GB",
    ram: 16,
    notes: "Okej dator överlag. RTX 4060 har begränsat VRAM."
  },

  alskar: [
    "FPS / Action (Singel)",
    "Taktisk FPS",
    "Battle Royale",
    "Hero shooter / MOBA-liknande FPS",
    "RPG / CRPG",
    "Open-World / Öppna världar",
    "Överlevnad / Crafting / Sandbox",
    "Sandbox / Creativity / World-building",
    "Life Simulation / Social Simulation",
    "Competitive Online (FPS etc.)"
  ],

  oppen: [
    "Boomer shooters",
    "Looter shooters",
    "Stealth-spel (smygarspel)",
    "Action Adventure",
    "3D Plattformare",
    "2D Plattformare",
    "Pusselspel i förstaperson",
    "Physics-baserade spel / bygg- och experimentspel",
    "Metroidvania-spel",
    "Taktiskt RPG / Turbaserat taktiskt RPG",
    "Interactive Story / Episodspel",
    "Arkad- och Simcade Racing",
    "Full racing simulator",
    "Övriga fordonsimulatorer",
    "Ubåt / Rymdsimulatorer",
    "Economy / Tycoon Games",
    "Multiplayer / Coop",
    "Fighting",
    "Beat-em-Up / Brawler",
    "Bullet hell / Shoot ’em up (Shmup)"
  ],

  undviker: [
    "JRPG",
    "ARPG / Action-rollspel",
    "Souls- och Soulslike",
    "Monsterfångar-RPG",
    "Visuella noveller / Storybaserade spel",
    "Realtidsstrategi (RTS)",
    "Turbaserade strategispel (TBS)",
    "4X-strategi",
    "Grand Strategy",
    "MOBA / Tactical Arena / Auto-battler",
    "Card-based Strategy / Digital CCG",
    "Sportspel",
    "Skräckspel",
    "Walking Simulator i förstaperson",
    "Peka & Klicka Äventyr",
    "Survival Horror FPS",
    "Arkadspel",
    "Rytmspel / Music / Rhythm action",
    "Match-3 spel",
    "Tabletop / Digital Board Games"
  ],

  ejValt: [
    "Tower Defense",
    "Kart-racing",
    "Flygsimulator",
    "Mech-/Robot-strategi eller action",
    "City building / Farming",
    "MMO (Onlinespel)",
    "Partyspel / Micro-games"
  ]
},
Emilia:
 {
		  plattformar: ["PC", "Nintendo Switch", ],
pcTier: "low",

  pc: {
    cpu: "AMD Ryzen 5 3550H",
    gpu: "NVIDIA GeForce GTX 1050 3GB",
    ram: 8,
    notes: "Bärbar dator. Här kan ENBART extremt lågt krävande spel vara aktuella. Dubbelkolla systemkrav."
  },
  alskar: [
  "3D Plattformare",
  "2D Plattformare",
  "Metroidvania-spel",
  "Taktiskt RPG / Turbaserat taktiskt RPG",
  "Fighting",
  "Arkadspel",
  "Klassiska arkadhallsspel"
],

oppen: [
  "Stealth-spel (smygarspel)",
  "Action Adventure",
  "JRPG",
  "Monsterfångar-RPG",
  "Visuella noveller / Storybaserade spel",
  "Kart-racing",
  "Mech-/Robot-strategi eller action",
  "Walking Simulator i förstaperson",
  "Peka & Klicka Äventyr",
  "Partyspel / Micro-games",
  "Beat-em-Up / Brawler",
  "Bullet hell / Shoot ’em up (Shmup)",
  "Match-3 spel",
  "Tabletop / Digital Board Games"
],

undviker: [
  "Souls- och Soulslike",
  "Open-World / Öppna världar",
  "Rogue-like / Rogue-lite spel",
  "MOBA / Tactical Arena / Auto-battler",
  "Arkad- och Simcade Racing",
  "Full racing simulator",
  "Flygsimulator",
  "Övriga fordonsimulatorer",
  "Ubåt / Rymdsimulatorer",
  "Sportspel",
  "Överlevnad / Crafting / Sandbox",
  "Sandbox / Creativity / World-building",
  "Life Simulation / Social Simulation",
  "Economy / Tycoon Games",
  "Kortspel / Deckbuilding"
],

ejValt: [
  "FPS / Action (Singel)",
  "Boomer shooters",
  "Looter shooters",
  "Taktisk FPS",
  "Battle Royale",
  "Hero shooter / MOBA-liknande FPS",
  "Pusselspel i förstaperson",
  "Physics-baserade spel / bygg- och experimentspel",
  "RPG / CRPG",
  "ARPG / Action-rollspel",
  "Realtidsstrategi (RTS)",
  "Turbaserade strategispel (TBS)",
  "4X-strategi",
  "Grand Strategy",
  "Tower Defense",
  "Card-based Strategy / Digital CCG",
  "City building / Farming",
  "Skräckspel",
  "Survival Horror FPS",
  "Competitive Online (FPS etc.)",
  "Multiplayer / Coop",
  "MMO (Onlinespel)",
  "Rytmspel / Music / Rhythm action"
]

},

Arvid: {
		  plattformar: ["PC", "Nintendo Switch", ],
pcTier: "extreme",

  pc: {
    cpu: "AMD Ryzen 7 7800X3D",
    gpu: "NVIDIA GeForce RTX 4070 SUPER 12GB",
    ram: 32,
    notes: "Han klarar allt i skrivande stund - riktigt bra dator sett till hur den är balanserad. Riktigt bra spel-CPU parad med stark GPU."
  },
  alskar: [
  "FPS / Action (Singel)",
  "Looter shooters",
  "Action Adventure",
  "3D Plattformare",
  "2D Plattformare",
  "Metroidvania-spel",
  "RPG / CRPG",
  "Monsterfångar-RPG",
  "Open-World / Öppna världar",
  "Interactive Story / Episodspel",
  "4X-strategi",
  "Grand Strategy",
  "Överlevnad / Crafting / Sandbox",
  "City building / Farming",
  "Multiplayer / Coop",
  "Tabletop / Digital Board Games"
],

  oppen: [
  "Boomer shooters",
  "Hero shooter / MOBA-liknande FPS",
  "Stealth-spel (smygarspel)",
  "Physics-baserade spel / bygg- och experimentspel",
  "JRPG",
  "Taktiskt RPG / Turbaserat taktiskt RPG",
  "ARPG / Action-rollspel",
  "Rogue-like / Rogue-lite spel",
  "Realtidsstrategi (RTS)",
  "Turbaserade strategispel (TBS)",
  "Tower Defense",
  "Arkad- och Simcade Racing",
  "Kart-racing",
  "Mech-/Robot-strategi eller action",
  "Sandbox / Creativity / World-building",
  "Economy / Tycoon Games",
  "Walking Simulator i förstaperson",
  "Peka & Klicka Äventyr",
  "Partyspel / Micro-games"
],

  undviker: [
  "Card-based Strategy / Digital CCG",
  "Sportspel",
  "Skräckspel",
  "Competitive Online (FPS etc.)",
  "MMO (Onlinespel)",
  "Beat-em-Up / Brawler",
  "Arkadspel",
  "Klassiska arkadhallsspel",
  "Bullet hell / Shoot ’em up (Shmup)",
  "Rytmspel / Music / Rhythm action",
  "Match-3 spel",
  "Kortspel / Deckbuilding"
],

  ejValt: [
  "Pusselspel i förstaperson",
  "Souls- och Soulslike",
  "MOBA / Tactical Arena / Auto-battler",
  "Flygsimulator",
  "Övriga fordonsimulatorer",
  "Ubåt / Rymdsimulatorer",
  "Life Simulation / Social Simulation",
  "Survival Horror FPS",
  "Fighting"
]

},

Vanessa: {
		  plattformar: ["PC", "Playstation 5", "Nintendo Switch", ],
pcTier: "mid",

  pc: {
    cpu: "AMD Ryzen 7 5800X3D",
    gpu: "NVIDIA GeForce RTX 4070 12GB",
    ram: 32,
    notes: "Bra allrounddator - med bra GPU."
},
alskar: [
  "Stealth-spel (smygarspel)",
  "3D Plattformare",
  "2D Plattformare",
  "RPG / CRPG",
  "Open-World / Öppna världar",
  "Action Adventure",
  "Interactive Story / Episodspel",
  "Rogue-like / Rogue-lite spel",
  "Turbaserade strategispel (TBS)",
  "Grand Strategy",
  "Överlevnad / Crafting / Sandbox",
  "Life Simulation / Social Simulation",
  "Skräckspel",
  "Walking Simulator i förstaperson",
  "Peka & Klicka Äventyr",
  "Survival Horror FPS",
  "Rytmspel / Music / Rhythm action"
],
oppen: [
  "Looter shooters",
  "Physics-baserade spel / bygg- och experimentspel",
  "JRPG",
  "Taktiskt RPG / Turbaserat taktiskt RPG",
  "ARPG / Action-rollspel",
  "Souls- och Soulslike",
  "Monsterfångar-RPG",
  "Card-based Strategy / Digital CCG",
  "Kart-racing",
  "Sandbox / Creativity / World-building",
  "City building / Farming",
  "Economy / Tycoon Games",
  "Multiplayer / Coop",
  "MMO (Onlinespel)",
  "Partyspel / Micro-games",
  "Arkadspel",
  "Kortspel / Deckbuilding"
],
undviker: [
  "FPS / Action (Singel)",
  "Battle Royale",
  "Hero shooter / MOBA-liknande FPS",
  "4X-strategi",
  "Tower Defense",
  "Arkad- och Simcade Racing",
  "Full racing simulator",
  "Flygsimulator",
  "Övriga fordonsimulatorer",
  "Mech-/Robot-strategi eller action",
  "Ubåt / Rymdsimulatorer",
  "Sportspel",
  "Competitive Online (FPS etc.)",
  "Match-3 spel",
"Tabletop / Digital Board Games"
],
ejValt: [
  "Boomer shooters",
  "Taktisk FPS",
  "Metroidvania-spel",
  "Realtidsstrategi (RTS)",
  "MOBA / Tactical Arena / Auto-battler",
  "Fighting",
  "Beat-em-Up / Brawler",
  "Klassiska arkadhallsspel",
  "Bullet hell / Shoot ’em up (Shmup)",
]
},


Niclas: {
		  plattformar: ["Playstation 5", "Nintendo Switch", ],

  pc: {
    cpu: "Intel Core m3",
    gpu: "Intel HD Graphics 515",
    ram: 8,
    notes: "Det finns ingen värld där Niclas dator kan användas för PC-recensioner. Han måste uppgradera."
  },
  alskar: [],
  oppen: [],
  undviker: [],
  ejValt: []
  }
}
};














